
<div style="margin: 20%">
    

    <div class="panel-body">
        <font size="5"> <a href="<?= $this->baseUrl() ?>/category/addcategory"  class="btn active btn-block btn-success btn-default" type="button"> اضف تصنيف</a> </font>
    </div>
    
    <div class="panel-body">
        <font size="5"> <a href="<?= $this->baseUrl() ?>/story"  class="btn active btn-block btn-success btn-default" type="button"> اضف قصة</a> </font>
    </div>
    
</div>