<br /><br />
<div  style="padding: 25px;" DIR="RTL">
    <form method="post" action="evaluatesite">
        <h3>نسبة استفادتك من المعلومات الموجودة بالموقع</h3>
        <input type="radio" name="q1" value="e" checked="true">ممتازة<br>
        <input type="radio" name="q1" value="vg">جيدة جدا<br>
        <input type="radio" name="q1" value="g">جيدة<br>
        <input type="radio" name="q1" value="w">ضعيفة<br>
        
        
        
        <h3>نسبة الصعوبة التي واجهتها في التعامل مع الموقع</h3>
        <input type="radio" name="q2" value="e" checked="true">ممتازة<br>
        <input type="radio" name="q2" value="vg" >جيدة جدا<br>
        <input type="radio" name="q2" value="g">جيدة<br>
        <input type="radio" name="q2" value="w">ضعيفة
        
        
        <h3>نسبة تميز الموقع عن باقي المواقع التي تعرض محتوي مشابه</h3>
        <input type="radio" name="q3" value="e" checked="true">ممتازة<br>
        <input type="radio" name="q3" value="vg">جيدة جدا<br>
        <input type="radio" name="q3" value="g">جيدة<br>
        <input type="radio" name="q3" value="w">ضعيفة<br><br>
        
        <h3>المقترحات:</h3>
        <textarea name="suggestion" cols="50" rows="5"></textarea><br><br>
        
        <input type="submit" name="submit" value="submit">
    </form>
</div>
