<br /><br />
<div DIR="RTL" style="padding: 25px;">
    <form method="post" action="evaluatechild">
        <h3>نسبة استفادة طفلك من المعلومات الموجودة بالموقع</h3>
        <input type="radio" name="q1" value="e" checked="true">ممتازة<br>
        <input type="radio" name="q1" value="vg">جيدة جدا<br>
        <input type="radio" name="q1" value="g">جيدة<br>
        <input type="radio" name="q1" value="w">ضعيفة<br>
        
        
        
        <h3>نسبة تأثير الموقع علي سلوك طفلك </h3>
        <input type="radio" name="q2" value="e" checked="true">ممتازة<br>
        <input type="radio" name="q2" value="vg" >جيدة جدا<br>
        <input type="radio" name="q2" value="g">جيدة<br>
        <input type="radio" name="q2" value="w">ضعيفة
        
        
        <h3>هل المعلومات المقدمة لطفل في الاسعافات الاولية تسببت في الحاق الاذي به او زملائه</h3>
        <input type="radio" name="q3" value="no" checked="true">لا<br>
        <input type="radio" name="q3" value="yes">نعم<br>
        
        
        
        <input type="submit" name="submit" value="submit">
    </form>
</div>
