

<br><br>

<div class="carousel slide" id="carousel-765973">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carousel-765973">
        </li>
        <li data-slide-to="1" data-target="#carousel-765973">
        </li>
        <li data-slide-to="2" data-target="#carousel-765973">
        </li>
    </ol>
    <div class="slider">
      <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img alt="" src="<?= $this->baseUrl() ?>/images/story1/HomeBackground.jpg"/>
                <img alt="" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" />
                <img alt="" src="<?= $this->baseUrl() ?>/images/3.png">
                <img alt="" src="<?= $this->baseUrl() ?>/images/4.jpg" />
                
            </div>
        </div>
   </div>
</div>
    
<br><br>
<div style="width:100%;margin: 5%">
    <div style="width:40%;float: left">
        <img alt="" class="roundrect" style="width:100%;" src="<?= $this->baseUrl() ?>/images/mission.jpg" /> 
    </div>
    
    <div style="width:40%;float: left;margin: 2%" dir="rtl">
        <ul>
        <li>
         نحن مجموعة من الشباب نتطلع الي
 تطوير المجتمع ومقتنعون تماما بأن هذا        
لن يتم الا من خلال زرع              
 المفاهيم الصحيحة في الاطفال
 بعيدا عن الطرق التقليدية للتعليم
        </li>
        <li> 
            و بدأنا بالسلوكيات و تعريف الطفل بالاسعافات الاولية
        </li>
        </ul> 
    </div>
</div>

<div style="clear: both"></div>

<div style="width:100%;margin: 5%" dir="rtl">
    <div style="width:40%; float: left">
        <img alt="" class="roundrect" style="width:100%;" src="<?= $this->baseUrl() ?>/images/siteDesc.jpg" /> 
    </div>
    
    <div style="width:40%;float: left;margin: 2%">
        <ul>
        <li>
            ينقسم الموقع الي جزء لاولياء الامور
            و جزء خاص بالطفل
        </li>
        <li> 
            <font style="color: #356635"><u>
            <b>الجزء الخاص بالطفل</b>
            </u></font><br>
            يستطيع الطفل مشاهدة قصص توصل له معلومة مفيدة
            
            <font style="color: #356635"><u>
            <br><b>الجزء الخاص باولياء الامور</b>
            </u></font><br>
            يستطيعون متابعة كل القصص التي يشاهدها ابنائهم 
            و تقييم ما يقدمه الموقع و كذلك تقييم مدي تأثير الموقع في الطفل
               
        </li>
        </ul> 
    </div>
</div>