
<br><br><br>
<?php
    if(isset($this->lock)){
?>
    <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4>
           ممممممممممممم
        </h4> <strong>لازم تعدي علي القصص بالترتيب و تجاوب علي الاسئلة الاول </strong>   <a href="" onclick="window.history.go(-1);
                return false;" class="alert-link">الرجوع</a> او <a href="../user">الرئيسية</a>
    </div>
<?php      
    }
    else if(isset($this->exist)){

?>

     <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4>
           ممممممممممممم
        </h4> <strong>هذه القصه تحتوي على صور ثابته فقط </strong>   <a href="" onclick="window.history.go(-1);
                return false;" class="alert-link">الرجوع</a> او <a href="../user">الرئيسية</a>
    </div>

<?php
    }

?>
<div  style="padding: 25px;">
    <table class = "table" DIR="rtl">
        <thead>
            <tr >
                <td> <strong>
                        القصص  </strong>
                </td>


            </tr>
        </thead>
        <?php
        foreach ($this->stories as $story) {
            if ($story['static'] == 0){
            ?>

            <tr class="success">
                <td>
                   <?= $story['name'] ?>
                </td>
                <td>
                    <a href="<?= $this->baseUrl() ?>/user/displaystory/story/<?=$story['path']?>">عرض صور متحركة</a>
                </td>

                <td>
                    <a href="<?= $this->baseUrl() ?>/user/displaysteps/story/<?=$story['path']?>">عرض صور ثابتة</a>
                </td>

            </tr>

            <?php
            }
            else{

            ?>
            <tr class="success">
                <td>
                   <?= $story['name'] ?>
                </td>
                <td>
                    
                </td>

                <td>
                    <a href="<?= $this->baseUrl() ?>/user/displaysteps/story/<?=$story['path']?>">عرض صور ثابتة</a>
                </td>

            </tr>
            <?php
            }
        }
        ?>

    </table>
</div>



